### PR TITLE
Account for a trailing dot in public suffix and registrable domain

### LINKED ISSUE #692: PSL references broken
It seems that https://publicsuffix.org/list/ got updated to remove the algorithm that was present there...

cc @dnsguru

### LINKED ISSUE #693: Can a registrable domain or public suffix have a trailing dot?
Normally `example.com.` and `example.com` are considered distinct origins, but https://github.com/publicsuffix/list/wiki/Format#formal-algorithm suggests

> A domain or rule can be split into a list of labels using the separator "." (dot). The separator is not part of any of the labels. Empty labels are not permitted, meaning that leading and trailing dots are ignored.

they might be considered same-site? That seems wrong to me and I would expect a trailing dot to be preserved as we preserve it everywhere else.

Neither URL nor HTML has trailing dot examples so I'm not sure if we explicitly considered this before.

cc @mikewest @sleevi @valenting @achristensen07 @dnsguru

(If the trailing dot is indeed significant follow-up is needed in at least https://github.com/httpwg/http-extensions/issues/1758 and Fetch's "`localhost`" check, which should then also consider "`localhost.`".)

### PR DESCRIPTION
**Pull request by annevk**
Also update the PSL algorithm reference. 

Fixes #692 and fixes #693.

(This depends on https://github.com/whatwg/infra/pull/446.)

***
<a href="https://whatpr.org/url/694.html" title="Last updated on May 3, 2022, 8:06 AM UTC (371b108)">Preview</a> | <a href="https://whatpr.org/url/694/3bc2e34...371b108.html" title="Last updated on May 3, 2022, 8:06 AM UTC (371b108)">Diff</a>

### CODE REVIEW

**Review by domenic — APPROVED** [review]

**Comment by dnsguru** [comment]
Just want to confirm, this needs no action from within PSL side, correct?  

 (PSL Volunteer here)

**Comment by annevk** [comment]
Yeah, that's correct. It would be good to get a heads up if the formal algorithm moves again or is modified in some fashion. Thanks!

**Comment by dnsguru** [comment]
>heads up

Challenge is, I can make a mental note to do this (and have), but I could
not have really known this would be something desired, as all "downline" is
opaque to us.

We really have no access to log files or visibility into who does what down
line.

There is only issues, wiki and readme on the repo.

We have only the mailing list but no other means of contacting *any*
parties that consume or use the PSL other than manipulating the headers
within the .dat file itself.

**Comment by annevk** [comment]
@dnsguru if you have some kind of process document for changes of this nature I'd be happy to add a line along the lines of "file an issue against the URL standard" which should encompass most browser usage.

**Comment by dnsguru** [comment]
Anne I apologize but I really dont understand how to action what you are
talking about

**Comment by annevk** [comment]
@dnsguru e.g., https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md outlines how to contribute to ECMAScript. In there, it says that if you change certain constructs that will have an impact downstream and encourages you to file issues upon certain known places (Web IDL, HTML, ...). It seems PSL could do something similar.

**Comment by dnsguru** [comment]
Thank you for the clarification Anne.  I will review that and see what I
can do, but #volunteer - may take a while

**Pull request merged**
