### PR TITLE
Clarify IPv6 serializer

### LINKED ISSUE #266: IPv6 serializer unclear
I'm having a hard time making sense of this:
> If compress pointer points to piece, append "::" to output if piece is address’s first piece and append ":" otherwise, and then run these substeps again with all subsequent pieces in address’s pieces that are 0 skipped or go the next step in the overall set of steps if that leaves no pieces.

### PR DESCRIPTION
**Pull request by annevk**
Fixes #266.

***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/ipv6-serializer/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/8386c7a...4af559d.html)

### CODE REVIEW

**Comment by domenic** [comment]
However you may find whatwg-url's former way of doing things to be simpler (no ignore0 variable):

```js
  for (let i = 0; i < address.length; ++i) {
    if (compressPtr === i) {
      if (i === 0) {
        output += "::";
      } else {
        output += ":";
      }

      i += seqResult.len - 1;
      continue;
    }

    output += address[i].toString(16);
    if (i !== address.length - 1) {
      output += ":";
    }
  }
```

**Comment by annevk** [comment]
What is seqResult.len?

**Comment by domenic** [comment]
It looks like it's the length of the longest zero sequence.

**Comment by annevk** [comment]
If it's immaterial to you I'd like to go with the patch. I don't really see a good translation of your code to English. We don't really have good for loop infrastructure.

**Comment by domenic** [comment]
Yeah, no problem for me.

**Pull request merged**
