### PR TITLE
Host parser UTF-8 decoding should fail, not U+FFFD

### LINKED ISSUE #215: Host parsing UTF-8 decoding can fail
Host parsing step 2 currently reads like this:
"Let domain be the result of UTF-8 decode without BOM on the percent decoding of UTF-8 encode on input."
If the UTF-8 decoding fails, it should explicitly say to return failure.  This matches Chrome, Firefox, and WebKit after https://bugs.webkit.org/show_bug.cgi?id=167330

### PR DESCRIPTION
**Pull request by annevk**
Tests: …

Fixes #215.

### CODE REVIEW

**Comment by annevk** [comment]
Tests: https://github.com/w3c/web-platform-tests/pull/4617.

**Comment by domenic** [comment]
This appears to be unnecessary. [ToASCII](http://www.unicode.org/reports/tr46/#ToASCII) applied to something with replacement characters will generate an error result, because [Processing](http://www.unicode.org/reports/tr46/#Processing) step 1 ends up in "disallowed" for the replacement character.

**Comment by annevk** [comment]
@achristensen07 it seems your implementation of ToASCII might be buggy.

@domenic thanks, I'll update this PR to instead make a note that implementations could fail early if they desire.

**Comment by annevk** [comment]
I should probably add an explicit test for https://�/ since Chrome and Firefox (haven't tested Edge) still turn that into something. But in general we need more IDNA tests.

**Comment by annevk** [comment]
Test for U+FFFD: https://github.com/w3c/web-platform-tests/pull/4639. I also updated the PR to make it a note instead.

**Pull request merged**
