### PR TITLE
Clarify the informative nature of referenced RFCs

### LINKED ISSUE #122: Section 3 (Hosts) should be non-normative
We noticed today that this section:

https://url.spec.whatwg.org/#hosts-%28domains-and-ip-addresses%29

Contradicts the URL spec parsing a bit.  The RFC for domains does not allow characters like `&`, but the URL spec parsing does allow it.

So section 3 should probably be marked non-normative.

### PR DESCRIPTION
**Pull request by annevk**
Fixes #122.

### CODE REVIEW

**Comment by annevk** [comment]
@wanderview, does this look okay?

**Comment by domenic** [comment]
It seems to me there are still two contradictory definitions of host. One that says "go look at the RFC", and one that is a component of URL records.

**Comment by annevk** [comment]
@domenic I don't understand? A URL's host is either null or a host. A host is a domain, IPv4 address, or IPv6 address. I don't think it's defined twice, where are you seeing that?

**Comment by domenic** [comment]
The concepts are defined twice: in 3 and in 3.2.

**Comment by annevk** [comment]
3.2 doesn't define a concept. It defines syntax.

**Comment by domenic** [comment]
Well, both define "host", and the URL Standard doesn't seem to use the syntax defined in the RFC referenced in 3. I think if you want to make this clear you should change 3.2 to "host syntax" and should point out that the RFC defines the concept but contains syntax that must be ignored in favor of the "host syntax" definition.

**Comment by annevk** [comment]
They define a different "host". Just like URL record's host is different. I mean this note says exactly that. Ignore the referenced RFCs for the purposes of syntax, parsing, and serialization...

**Comment by domenic** [comment]
My point is that having two dfns with the same text is extremely confusing especially when it's easy to read both as defining syntax.

**Comment by annevk** [comment]
That is a more general problem. I guess we could introduce the disambiguation terms "host record" and "host string" here too, and similar for host's sub parts, but that's a bigger issue than this.

**Comment by domenic** [comment]
Well, all I can say is this PR doesn't make things clearer for me (see also #118) but maybe it helps @wanderview.

**Comment by annevk** [comment]
I think that is worth explaining separately from the informative nature of the RFCs.

**Comment by annevk** [comment]
I still don't have a plan for clarifying out the various definitions of host/query/port/etc. but this seemed like a good clarification either way.

**Pull request merged**
