### PR TITLE
IPv4 parser: handle the empty string

### LINKED ISSUE #79: Parsing an empty host
If I’m reading the parsing algorithm correctly, parsing `some-non-special-scheme:///` causes the host parser to be called with an empty string. Since _domain to ASCII_ sets _VerifyDnsLength_ to false, _asciiDomain_ is also empty (not failure) and IPv4 parsing is called with an empty string. There, _parts_ is first a list of one empty string, then an empty list:

> Let parts be input split on ".".
> If the last item in parts is the empty string, set syntaxViolationFlag and remove the last item from parts.

Later, _numbers_ stays empty and some of the steps are nonsensical when they talk about the last item of _numbers_.

So:
- The IPv4 parser should probably return failure for the empty string as a first step
- This would make the host of this example URL an empty domain. Should it be null instead?

### PR DESCRIPTION
**Pull request by annevk**
This is a theoretical issue once #185 lands, but as discussed it seems
good to address this anyway. Fixes #79.

### CODE REVIEW

**Comment by annevk** [comment]
This doesn't require test changes as you cannot hit this scenario currently.

**Comment by annevk** [comment]
This should land after 185, otherwise the added comment is a little off.

**Comment by domenic** [comment]
Can't really test until we figure out https://github.com/whatwg/url/pull/185; please ping me again when we finish that, if I forget.

**Comment by annevk** [comment]
@domenic consider yourself pinged.

**Pull request merged**
