### PR TITLE
Editorial: Update link to maintainer guidlines

### PR DESCRIPTION
**Pull request by snuggs**
Addresses:
  - whatwg/meta#65

### CODE REVIEW

**Comment by annevk** [comment]
Something went wrong here. Presumably when rebasing you incorrectly restored the old text?

**Comment by snuggs** [comment]
@annevk  What happens when you move too fast and don't realize you already did it. :-( Can close! :-D

**Comment by annevk** [comment]
Well, we still have the incorrect TEAM.md link here. I can fix that too though.

**Comment by snuggs** [comment]
@annevk rebased properly. How's this look?

**Comment by annevk** [comment]
I think we should use #365 instead at this point as that fixes more.

**Comment by snuggs** [comment]
@annevk  copy that!

**Pull request closed without merging**
