### PR TITLE
Added URLs example.com/demo/ column to table

### PR DESCRIPTION
**Pull request by paulvollmer**
i added an example to the URLs table to show the behaviour of `example.com/demo/` and `example`

***
<a href="https://whatpr.org/url/441.html" title="Last updated on Jun 5, 2019, 1:05 PM UTC (30adb81)">Preview</a> | <a href="https://whatpr.org/url/441/8809598...30adb81.html" title="Last updated on Jun 5, 2019, 1:05 PM UTC (30adb81)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
Thanks, would you like to add your name to the Acknowledgments section too?

**Comment by annevk** [comment]
You'll also need to sign https://participate.whatwg.org/agreement.

**Comment by paulvollmer** [comment]
I signed the participation agreement and added me to the Acknowledgments section.

I think the url resolving of base `https://example.com/demo` and input `example` with output `https://example.com/example` should be the same as the output `https://example.com/demo/example` for base `https://example.com/demo/`(slash at the end) with input `example`

because if input `../example` of base `https://example.com/demo` the output should be `https://example.com/example`

**Comment by annevk** [comment]
Thanks! I'm not sure I understand your last comment fully. All the existing examples are correct, no?

**Pull request closed without merging**
